import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Pochaevsk&display=swap" rel="stylesheet" />
      </Head>
      <div>
        <main className={styles.main}>
          <div className={styles.header}>
            <div className={styles.secondary_title}>The 1st</div>
            <div className={styles.title}>Masters of the Bulge</div>
            <div className={styles.secondary_title}>2025</div>
          </div>

          <div>
            <button>Leaderboard</button>
            <button>Pool</button>
          </div>
        </main>
      </div>
    </>
  );
}
