const RANKINGS = {
  "T1": [
    "Scottie Scheffler",
    "Rory McIlroy"
  ],
  "T2": [
    "Jon Rahm",
    "Collin Morikawa",
    "Xander Schauffele",
    "Ludvig Aberg",
    "Bryson DeChambeau",
    "Justin Thomas",
    "Jordan Spieth",
    "Joaquin Niemann",
    "Hideki Matsuyama",
    "Brooks Koepka"
  ],
  "T3a": [
    "Viktor Hovland",
    "Tommy Fleetwood",
    "Patrick Cantlay",
    "Tyrrell Hatton",
    "Shane Lowry",
    "Russell Henley",
    "Cameron Smith",
    "Min Woo Lee",
    "Robert MacIntyre",
    "Akshay Bhatia",
    "Will Zalatoris",
    "Sergio Garcia"
  ],
  "T3b": [
    "Corey Conners",
    "Tony Finau",
    "Sepp Straka",
    "Jason Day",
    "Wyndham Clark",
    "Tom Kim",
    "Brian Harman",
    "Sahith Theegala",
    "Patrick Reed",
    "Keegan Bradley",
    "Dustin Johnson"
  ],
  "T4a": [
    "Aaron Rai",
    "Daniel Berger",
    "Sungjae Im",
    "Justin Rose",
    "Davis Thompson",
    "Billy Horschel",
    "Byeong Hun An",
    "Sam Burns",
    "Lucas Glover",
    "Adam Scott",
    "J.J. Spaun",
    "Michael Kim",
    "Taylor Pendrith",
    "Matt Fitzpatrick",
    "Maverick McNealy",
    "Phil Mickelson",
    "Thomas Detry",
    "Denny McCarthy"
  ],
  "T4b": [
    "Stephan Jaeger",
    "Harris English",
    "Cameron Young",
    "Laurie Canter",
    "Max Greyserman",
    "J.T. Poston",
    "Nicolai Hojgaard",
    "Nick Taylor",
    "Rasmus Hojgaard",
    "Cam Davis",
    "Joe Highsmith",
    "Christiaan Bezuidenhout",
    "Max Homa",
    "Chris Kirk",
    "Austin Eckroat",
    "Tom Hoge",
    "Nico Echavarria",
    "Kevin Yu",
    "Nick Dunlap"
  ],
  "T5": [
    "Matt McCarty",
    "Jhonattan Vegas",
    "Matthieu Pavon",
    "Charl Schwartzel",
    "Bubba Watson",
    "Danny Willett",
    "Adam Schenk",
    "Thriston Lawrence",
    "Davis Riley",
    "Justin Hastings",
    "Brian Campbell",
    "Zach Johnson",
    "Jose Luis Ballester",
    "Patton Kizzire",
    "Rafael Campos",
    "Evan Beck",
    "Noah Kent",
    "Hiroshi Tai",
    "Bernhard Langer",
    "Angel Cabrera",
    "Vijay Singh",
    "Mike Weir",
    "Jose Maria Olazabal",
    "Fred Couples"
  ]
};

export default RANKINGS